name: CI

on: 
  pull_request:
    branches: [develop]

  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use nodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - run: npm ci
      - run: npm run test -- --coverage
        env: 
          CI: true
      - name: Build project
        if: github.even_name== 'push'
        run: npm run build
      
      - name: Deploy project
        if: github.even_name== 'push'
        run: npx surge --project ./build --domain
          short-duck.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}